project:
  render:
    - days/day0_setup.qmd
    - days/day1_reproducible_project.qmd
    - modules/git_github.qmd
    - modules/containers_docker_podman.qmd
    - modules/public_data_retrieval.qmd
    - modules/reference_genomes.qmd

website:
  sidebar:
    contents:
      - section: "Day-by-day lessons"
        contents:
          - text: "Day 0 - Setup"
            href: days/day0_setup.qmd
          - text: "Day 1 - Reproducible project"
            href: days/day1_reproducible_project.qmd
      - section: "Core modules"
        contents:
          - modules/git_github.qmd
          - modules/containers_docker_podman.qmd
          - modules/public_data_retrieval.qmd
          - modules/reference_genomes.qmd
