project:
  render:
    - days/day0_setup.qmd
    - modules/git_github.qmd
    - modules/containers_docker_podman.qmd

website:
  sidebar:
    contents:
      - section: "Day-by-day lessons"
        contents:
          - text: "Day 0 - Setup"
            href: days/day0_setup.qmd
      - section: "Core modules"
        contents:
          - modules/git_github.qmd
          - modules/containers_docker_podman.qmd
