FROM docker.io/mambaorg/micromamba:1.5.10

RUN micromamba install -y -n base -c conda-forge -c bioconda \
      r-base=4.3 \
      r-dplyr \
      r-ggplot2 \
      r-readr \
      r-tibble \
      r-pheatmap \
      bioconductor-deseq2 \
      bioconductor-complexheatmap \
      bioconductor-genomicranges \
      bioconductor-iranges \
      bioconductor-rtracklayer \
      bioconductor-genomation \
      bioconductor-rsamtools \
      bioconductor-genomicalignments \
    && micromamba clean -a -y

WORKDIR /work
