FROM docker.io/mambaorg/micromamba:1.5.10

RUN micromamba install -y -n base -c conda-forge -c bioconda \
      sra-tools=3.4.1 \
      pigz=2.8 \
      curl \
      ca-certificates \
    && micromamba clean -a -y

WORKDIR /work