FROM docker.io/library/python:3.11-slim-bookworm

ARG MULTIQC_VERSION=1.22.3

RUN python -m venv /opt/multiqc \
    && /opt/multiqc/bin/pip install --no-cache-dir --upgrade pip \
    && /opt/multiqc/bin/pip install --no-cache-dir "multiqc==${MULTIQC_VERSION}"
ENV PATH="/opt/multiqc/bin:${PATH}"
WORKDIR /work
CMD ["/bin/bash"]
