FROM docker.io/mambaorg/micromamba:1.5.10

RUN micromamba install -y -n base -c conda-forge -c bioconda \
      phantompeakqualtools=1.2.2 \
      idr=2.0.4.2 \
      samtools=1.20 \
    && micromamba clean -a -y

WORKDIR /work
