project:
  name: "example_ngs_project"
  organism: "Helicobacter pylori"
  threads: 2
  runtime: "docker"
reference:
  assembly_accession: "GCF_025998455.1"
  chromosome_accession: "NZ_AP026446.1"
  fasta: "reference_genome/genome.fa"
  annotation: "reference_genome/annotation.gff3"
  bowtie2_index_prefix: "reference_genome/bowtie2_index/genome"
  genome_size: "1696601"
