project:
  name: "example_ngs_project"
  organism: "Helicobacter pylori"
  threads: 2
  runtime: "docker"
reference:
  fasta: "data/reference/genome.fa"
  annotation: "data/reference/annotation.gff3"
  bowtie2_index_prefix: "results/reference/bowtie2_index/genome"
  genome_size: "1.7e6"

